version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: scigraph-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - scigraph-network

  redis:
    image: redis:7-alpine
    container_name: scigraph-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scigraph-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: scigraph-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/scigraph?authSource=admin
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - scigraph-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: scigraph-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - scigraph-network

volumes:
  mongodb_data:
  redis_data:

networks:
  scigraph-network:
    driver: bridge
